package day5.java;
public class codingday5 {
    public static void main(String[] args) {
        //Contoh penggunaan byte (tipe data bilangan bulat 8 bit)
        byte umur = 18;
        System.out.println("Umur :" + umur);
        
        //Contoh penggunaan short (tipe data bilangan bulat 16 bit)
        short tanggalLahir = 20; 
        System.out.println("Tanggal Lahir: " + tanggalLahir );
        
        //Contoh penggunaan int (tipe data bilangan bulat 32 bit)
        int tahun = 2025;
        System.out.println("Tahun :" + tahun);
        
        //Contoh penggunaan long (tipe data bilangan bulat 64 bit)
        long uangku = 5000000000000L; 
        System.out.println("Saldo ATM-ku di masa depan: Rp " + uangku);
        
    }
}
